# Generated by Django 3.2.8 on 2022-03-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200, null=True)),
                ('teamlead', models.CharField(max_length=200, null=True)),
                ('leadphone', models.CharField(max_length=200, null=True)),
                ('leademail', models.CharField(max_length=200, null=True)),
                ('member2', models.CharField(max_length=200, null=True)),
                ('member3', models.CharField(max_length=200, null=True)),
                ('member4', models.CharField(max_length=200, null=True)),
                ('repolink', models.CharField(max_length=500, null=True)),
                ('livelink', models.CharField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
