# Generated by Django 3.2.8 on 2022-03-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='leademail',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='leadphone',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='livelink',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member2',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member3',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member4',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='repolink',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='teamlead',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='teamname',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
