# Generated by Django 3.2.8 on 2022-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0002_auto_20220329_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='member2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='teamlead',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='teamname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
