# Generated by Django 4.0.1 on 2023-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0004_participant_levelchoice_participant_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='levelchoice',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced')], default='Beginner', max_length=200, null=True),
        ),
    ]
