# Generated by Django 4.0.1 on 2023-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0005_alter_participant_levelchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='codingvideolink',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
